#!/bin/sh
set -e

version="$1"
if [ -z "$version" ]; then
  echo "Usage: <version>"
  exit 1
fi

git checkout -b release

command -v json>/dev/null || npm i -g json
json -I -e "this.version='Version $version'" -f view.json
make

git add view.json
git commit -m "Version $version"
tag="v$version"
git tag "$tag"
git push origin "$tag"

cd build
for file in ./*; do
  newname="$(echo "$file" | sed "s/nda-/$version/")"
  mv "$file" "$newname"
done
